ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
    ssid="Apollo Network"
    # Use standard psk field for both WPA3 and WPA2 fallback
    psk="Apollo123*"
    # Allow the board and router to negotiate the best protocol
    key_mgmt=SAE WPA-PSK
    # 1 = PMF Optional
    ieee80211w=1
}
