#@TYPE: Machine
#@NAME: Mustang NXP (i.MX8M Plus EVK)
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Mustang based on NXP i.MX8M Plus EVK

require conf/machine/imx8mp-lpddr4-evk.conf

# Autoload NXP Wi-Fi kernel driver
KERNEL_MODULE_AUTOLOAD += "moal"
